conda-forge/openff-toolkit-feedstock

.ci_support/linux_64_.yaml, conda-forge.yml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> openff-toolkit 0.9.0

.ci_support/linux_64_.yaml, .scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, LICENSE.txt, README.md, recipe/meta.yaml
=> Add packaging to required dependencies

recipe/meta.yaml
=> fix SHA after GH updated tarball contents a few minutes after last release

recipe/meta.yaml
=> v0.10.6 release

.ci_support/linux_64_.yaml, .circleci/config.yml, .scripts/build_steps.sh, LICENSE.txt, build-locally.py, recipe/conda_build_config.yaml, recipe/meta.yaml, recipe/test_openff_toolkit.py
=> Release 0.11.0rc1

.ci_support/linux_64_.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml, recipe/test_openff_toolkit.py
=> Add Interchange to builds

.ci_support/linux_64_.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> 0.11.0 build 1 [clean up recipe to remove mentions of rc channels and pins]

recipe/meta.yaml
=> openff-toolkit 0.11.1

recipe/meta.yaml
=> Release 0.11.2

recipe/meta.yaml
=> 0.11.2 build 2 - pin pint

.circleci/config.yml, .scripts/build_steps.sh, recipe/meta.yaml
=> 0.11.3 build 0

recipe/meta.yaml
https://github.com/openforcefield/openff-toolkit/issues/1487
Checklist
=> Pin to compatible `packaging`

recipe/meta.yaml
=> 0.12.1 build 1 downpin to avoid breaks in upcoming interchange 0.3.0 release

recipe/meta.yaml
=> 0.13.0 build 0

recipe/meta.yaml
=> 0.13.2 build 0

recipe/meta.yaml
=> 0.14.0 build 0

recipe/meta.yaml
=> Remove ipywidgets pin

recipe/meta.yaml
=> Constrain `numpy =1`

recipe/meta.yaml
=> 0.14.2 build 0

recipe/meta.yaml
=> 0.14.3 build 0

recipe/meta.yaml
=> 0.14.4 build 0 or 1 (I accidentally committed to c-f main initially instead of my fork)

.scripts/build_steps.sh, .scripts/logging_utils.sh, recipe/meta.yaml
Adds openff-nagl and openff-nagl-models to examples package
Checklist
=> 0.14.4 build 1

.azure-pipelines/azure-pipelines-linux.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, recipe/meta.yaml
=> Release 0.14.5

.gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, recipe/meta.yaml
=> 0.15.0 build 0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, build-locally.py, recipe/meta.yaml
=> 0.16.0 build 0

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Keep toolkit on Interchange 0.3 line

.scripts/build_steps.sh, recipe/meta.yaml
=> 0.16.2 build 0

recipe/meta.yaml
=> Release 0.16.4

.ci_support/linux_64_.yaml, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Make off-label build for Interchange testing

recipe/meta.yaml
=> remove zstandard constraint

.scripts/build_steps.sh, azure-pipelines.yml, recipe/meta.yaml
=> 0.16.6 build 0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, build-locally.py, recipe/meta.yaml, recipe/test_openff_toolkit.py
=> Release 0.16.7

.ci_support/linux_64_.yaml, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Allow Python 3.13 at runtime

.scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
=> Unrestrict openff-toolkit-examples python versions

recipe/meta.yaml
=> 0.16.9 build 0

.ci_support/linux_64_.yaml, README.md, recipe/meta.yaml
=> 0.17.1 build 0
